services:
  # Backend Server
  - type: web
    name: shesocial-server
    runtime: node
    plan: free
    buildCommand: npm run build:server
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: CORS_ORIGIN
        value: https://shesocial-client.onrender.com
      - key: CLIENT_URL
        value: https://shesocial-client.onrender.com
    healthCheckPath: /health

  # Frontend Static Site
  - type: web
    name: shesocial-client
    runtime: static
    buildCommand: npm run build:client
    staticPublishPath: ./client/dist
    envVars:
      - key: VITE_API_URL
        value: https://shesocial-server.onrender.com/api
      - key: VITE_APP_ENV
        value: production
    routes:
      - type: rewrite
        source: /*
        destination: /index.html