services:
  # Backend Server
  - type: web
    name: shesocial-server
    env: node
    region: singapore
    plan: starter
    buildCommand: npm run build:server
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: CORS_ORIGIN
        value: https://shesocial.onrender.com
      - key: CLIENT_URL
        value: https://shesocial.onrender.com

  # Frontend Static Site
  - type: static
    name: shesocial-client
    env: static
    region: singapore
    buildCommand: npm run build:client
    staticPublishPath: ./client/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        value: https://shesocial-server.onrender.com/api
      - key: VITE_APP_ENV
        value: production